- name: Install OpenJDK 21 and Git on Amazon Linux 2023
  hosts: ec2
  become: true
  tasks:
    - name: Install OpenJDK 21 (Amazon Corretto)
      yum:
        name: java-21-amazon-corretto-devel
        state: present

    - name: Set JAVA_HOME and update PATH
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0755'

    - name: Install git
      yum:
        name: git
        state: present

    - name: Download MySQL 8.0 Yum Repository RPM
      get_url:
        url: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
        dest: /tmp/mysql80-community-release.rpm

    - name: Install MySQL Yum Repository
      yum:
        name: /tmp/mysql80-community-release.rpm
        state: present

    - name: Enable MySQL 8.0 Module
      command: dnf module disable mysql -y
      args:
        warn: false

    - name: Install MySQL 8.0 Server
      yum:
        name: mysql-community-server
        state: present

    - name: Enable and start mysqld service
      systemd:
        name: mysqld
        enabled: yes
        state: started