- name: Install OpenJDK 21 and Git on Amazon Linux 2023
  hosts: ec2
  become: true
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:
        timeout: 300
        
    - name: Install OpenJDK 21 (Amazon Corretto)
      yum:
        name: java-21-amazon-corretto-devel
        state: present

    - name: Set JAVA_HOME and update PATH
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0755'

    - name: Install git
      yum:
        name: git
        state: present

- name: Install MySQL 8.0 client on Amazon Linux 2023
  hosts: ec2
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Copy MySQL Yum Repository RPM to EC2
      ansible.builtin.copy:
        src: mysql80-community-release-el9-1.noarch.rpm
        dest: /tmp/mysql80-community-release.rpm

    - name: Import MySQL GPG key
      rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

    - name: Import MySQL 2022 GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

    - name: Import MySQL 2023 GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

    - name: Install MySQL Yum Repository RPM
      ansible.builtin.dnf:
        name: /tmp/mysql80-community-release.rpm
        state: present

    - name: Install MySQL 8.0 client and related packages
      dnf:
        name:
          - mysql
          - mysql-community-client
        state: present

    - name: Install Python3, pip, and MySQL build dependencies
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - gcc
          - python3-devel
          - mysql-devel
        state: present
        update_cache: yes

    - name: Install mysqlclient using pip
      ansible.builtin.pip:
        name: mysqlclient

    # - name: Install Python MySQL dependencies
    #   ansible.builtin.dnf:
    #     name:
    #       - python3
    #       - python3-pip
    #     state: present

    # - name: Install mysqlclient for Ansible MySQL modules
    #   ansible.builtin.pip:
    #     name: mysqlclient

    - name: Check MySQL connection with root user
      community.mysql.mysql_info:
        login_user: root
        login_password: "rootroot"
        login_host: "test-rds.c9w2ki24y6sz.ap-northeast-1.rds.amazonaws.com"

    - name: Check MySQL connection with password
      community.mysql.mysql_info:
        login_user: root
        login_password: "rootroot"
        login_host: "test-rds.c9w2ki24y6sz.ap-northeast-1.rds.amazonaws.com"

    - name: Create a database called testdb
      community.mysql.mysql_db:
        name: testdb
        state: present
        login_user: root
        login_password: "rootroot"
        login_host: "test-rds.c9w2ki24y6sz.ap-northeast-1.rds.amazonaws.com"

    - name: Create students table in the database
      community.mysql.mysql_query:
        login_user: root
        login_password: "rootroot"
        login_host: "test-rds.c9w2ki24y6sz.ap-northeast-1.rds.amazonaws.com"
        login_db: testdb 
        query: |
          CREATE TABLE IF NOT EXISTS students (
            studentId INT PRIMARY KEY AUTO_INCREMENT,
            name VARCHAR(50) NOT NULL,
            kana VARCHAR(50) NOT NULL,
            nickname VARCHAR(50),
            mail VARCHAR(50) NOT NULL,
            area VARCHAR(50),
            age INT,
            sex VARCHAR(10),
            remark TEXT,
            is_Deleted BOOLEAN
          );