- name: Create test.txt on EC2
  hosts: ec2
  become: false
  tasks:
    - name: Create test.txt in home directory
      copy:
        dest: "~/test.txt"
        content: "This is a test file created by Ansible via GitHub Actions.\n"